services:
  - type: web
    name: ryanmdewey-site
    env: static
    rootDir: frontend         # Tells Render to only build/deploy from this folder
    buildCommand: ""          # No build step needed (unless you later add one)
    staticPublishPath: .      # Serve the HTML/CSS directly from here
    routes:
      - type: rewrite
        source: /blog/(.*)
        destination: /blog/$1
      - type: rewrite
        source: /blog
        destination: /frontend/blog/index.html
      - type: rewrite
        source: /projects
        destination: /projects.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /skills
        destination: /skills.html
      - type: rewrite
        source: /resume
        destination: /resume.html
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /
        destination: /index.html
