services:
  - type: web
    name: ryanmdewey-site
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /blog/(.*)
        destination: /blog/$1
      - type: rewrite
        source: /blog
        destination: /blog/index.html
      - type: rewrite
        source: /projects
        destination: /projects.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /
        destination: /index.html
