services:
  - type: web
    name: ryanmdewey-site
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: vite preview --port $PORT
    staticPublishPath: build

    routes:
      - type: rewrite
        source: /.*
        destination: /
