services:
  - type: web
    name: ryanmdewey-site
    env: node
    rootDir: .                # Root of your repo (or change to "client" or "src" if needed)
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: build
    buildFilter:
      paths:
        - package.json
        - src/**/*
        - public/index.html

    autoDeploy: true

    routes:
      - type: rewrite
        source: /blog
        destination: /
      - type: rewrite
        source: /academy
        destination: /
      - type: rewrite
        source: /resume
        destination: /
      - type: rewrite
        source: /contact
        destination: /
      - type: rewrite
        source: /skills
        destination: /
      - type: rewrite
        source: /projects
        destination: /
      - type: rewrite
        source: /experience
        destination: /
      - type: rewrite
        source: /
        destination: /
      - type: rewrite
        source: /.*     # catch-all fallback
        destination: /
